spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

application:
  security:
    jwt:
      secret-key: KVABHD/yeS0sZ85kQq4hlFNXYc0ZlktGRPdEW9MTEIE=
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days